#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - jq
  - aws-cli
  - btrfs-progs
  - python27-pip
  - sed

runcmd:
  - pip install -U awscli boto3
  - curl -o /opt/ebs-autoscale.tar.gz http://cromwell-aws-batch.s3.amazonaws.com/files/ebs-autoscale.tar.gz
  - cd /opt/ && tar -xzf ebs-autoscale.tar.gz && rm -f ebs-autoscale.tar.gz
  - sh /tmp/ebs-autoscale/bin/bootstrap-ebs-autoscale.sh /scratch /dev/xvdc  2>&1 > /var/log/bootstrap-ebs-autoscale.log
