#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - btrfs-progs
  - python27-pip
  - sed
  - git

runcmd:
  - pip install -U awscli boto3
  - cd /opt && git clone https://github.com/delagoya/ebs-autoscale.git
  - sh /opt/ebs-autoscale/bin/init-ebs-autoscale.sh /scratch /dev/xvdc  2>&1 > /var/log/init-ebs-autoscale.log
